v2022.08.0
conda-forge/geocat-comp-feedstock pull request #7
Opened 2022-09-07 17:16 UTC by marodrig

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2022-09-07 17:16 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2022-09-07 17:16 UTC, marodrig commented
@conda-forge-admin, please rerender

2022-09-08 19:03 UTC, anissa111 requested changes

2022-09-08 19:03 UTC, anissa111 commented on recipe/meta.yaml
> +    - numpy
Probably shouldn't add trailing whitespace here

2022-09-08 19:03 UTC, anissa111 commented on recipe/meta.yaml
> +    - numba
We aren't actually using numba in geocat-comp (yet), I don't think we should add it to the `meta.yml` here.

2022-09-09 15:13 UTC, anissa111 commented
@conda-forge-admin, please rerender

2022-09-09 18:56 UTC, anissa111 commented on recipe/meta.yaml
> +    - numba
Note for future developers: numba is needed by xskillscore

2022-09-09 19:06 UTC, anissa111 approved these changes

2022-09-09 19:08 UTC, merged